### ISSUE TITLE
Хранимые процедуры

### ISSUE THREAD

**Issue by Akllike** [Vasiliy-Makogon/Database#13]
Хотелось бы видеть в дальнейшем работу с функциями и хранимыми процедурами. Планируется такая реализация?

**Comment by Vasiliy-Makogon** [comment]
Здравствуйте!

> Планируется такая реализация?

Код данной библиотеки писался для определенного проекта и там не было потребности в ХП.
Сейчас, не погружаясь в детали, хочу заметить, что идеология библиотеки - это, фактически, один метод query(), который исполняет SQL-код. Т.е. библиотека должна оставаться максимально простой, без излишних наворотов. 

С другой стороны я не могу так сразу сказать, успешно ли библиотека справляется с ХП/функциями и насколько это удобно для конечного пользователя. Если будут merge request запросы от пользователей и они будут соответствовать идеологии библиотеки в плане простоты, я одобрю эти запросы.

Сам сейчас этим заниматься не имею времени.
