### ISSUE TITLE
SQL-Inj: Float escaping error

### ISSUE THREAD

**Issue by defaultpage** [Vasiliy-Makogon/Database#2]
Code:
```
$queryResult = $db->query('SELECT ?d, ?d', '1.5, version() -- ', '1.5');
$data = $queryResult->fetch_assoc();
```
Result in debugger:

![Array ( [1.5] => 1.5 [version()] => 10.1.9-MariaDB )](https://habrastorage.org/webt/59/d8/95/59d8952dc78ea133804130.png)

___
Function isFloat() return "true" ($val = `'1.5, version() -- '`), because `$val+0` return `1.5` 
```
return is_float($val + 0);
```
After that function getValueFloatType() return `'1.5, version() -- '` without escaping:

```
 if ($this->isFloat($value)) {
     return $value;
 }
```
___
P.S.: Tested on PHP <= 7.0.14. On PHP 7.1.0 line `return is_float($val + 0);` causes an error:
><b>Notice</b>:  A non well formed numeric value

**Comment by Vasiliy-Makogon** [comment]
Спасибо, всё так.
