### ISSUE TITLE
LIKE не работает как надо?

### ISSUE THREAD

**Issue by lopar** [Vasiliy-Makogon/Database#4]
Таблица:

 id | name 
 -- | --
 1 | Тестовое имя 1
 2 | Проверочное имя 2
 3 | Тестовое имя 3 

Формирую запрос:
```
…
$name = 'Тестовое';
…->query('SELECT COUNT(`id`) FROM `table` WHERE `name` LIKE "?S"',$name . '%')
```

Возвращает запрос:
`[SELECT COUNT(`id`) FROM `table` WHERE `name` LIKE "Тестовое\%"]`

Хотя должен возвращать:
`[SELECT COUNT(`id`) FROM `table` WHERE `name` LIKE "Тестовое%"]`

В результате запросы LIKE просто не выполняются, возвращая пустое место вместо реального значения.
Попытки делать штуки вроде:
```
…
$name = 'Тестовое';
$preparedName = $name . '%';
… query('SELECT COUNT(`id`) FROM `table` WHERE `name` LIKE "?S"',$preparedName)
```
Тоже ни к чему не приводят.

**Comment by Vasiliy-Makogon** [comment]
Здравствуйте. 
Нужно вот так: 

`$name = 'Тестовое';
…->query('SELECT COUNT(`id`) FROM `table` WHERE `name` LIKE "?S%"', $name)`

Знак `%`, переданный в качестве параметра в метод query(), естественно экранируется символом `\`, т.к. вполне возможна ситуация, когда возникнет необходимость искать строку, содержащую служебный символ `%`. Также, экранируется и символ `_`.
