### ISSUE TITLE
PHPStorm SQL Inspections

### ISSUE THREAD

**Issue by nazbav** [Vasiliy-Makogon/Database#5]
В ходе работы с вашим расширением, возникли головные боли, тошнота, рвота и другие симптомы, присущие коду, переполненном сообщениями об ошибках (это такие, красненькие черточки, с правой стороны)
![image](https://user-images.githubusercontent.com/21163205/77535583-42aca200-6eb4-11ea-8de9-cf0acf3e6e34.png)

Частично решить эту проблему, за исключением пожалуй, использования заполнителя в SET удалось вот так вот (тут мы игнорируем заполнители):

![image](https://user-images.githubusercontent.com/21163205/77535041-4e4b9900-6eb3-11ea-9144-ba2ed16c685c.png)

Но при работе с запросом, пример которого, даже, приведен в описании к данному классу:

![image](https://user-images.githubusercontent.com/21163205/77535347-e8134600-6eb3-11ea-8b71-76be1aa75be0.png)

Возникает ошибка, связанная с отсутствием оператора присвоения (что логично):

![image](https://user-images.githubusercontent.com/21163205/77535830-bc449000-6eb4-11ea-8ce3-8abf788863ec.png)

`Хотелось бы узнать какими методами для решения данной "неприятной красноты кода", пользуетесь Вы, при работе в редакторах с проверками?`

Технически, это решается модификацией вашего класса, и добавлением `=0`, после работы с заполнителем ассоциативного массива:

![image](https://user-images.githubusercontent.com/21163205/77536550-f3677100-6eb5-11ea-9c87-f0bdcc68fde5.png)
![image](https://user-images.githubusercontent.com/21163205/77536596-05e1aa80-6eb6-11ea-8aa0-c4ecaa5d62a5.png)

**Comment by nazbav** [comment]
Были сомнения :D

**Comment by Vasiliy-Makogon** [comment]
Здравствуйте.
Проверка корректности SQL-запроса на уровне PHPStorm является частным случаем, я не давал никаких гарантий относительно этого фактора. И, если честно, я впервые вижу в шторме проверку синтаксиса SQL, подскажите, где она включается? Из "коробки", насколько я понимаю, этого нет - у меня никогда не было "ошибок" валидации кода на уровне редактора.

**Comment by nazbav** [comment]
Сначала? он требует подрубить базу (видимо, из-за этого у Вас все желтое), далее, основываясь на том, что база подключена, и мы знаем название колонок\таблиц\ключи и т.д.,
включаются проверки SQL запросов.

Первый костыль заключался в игнорировании заполнителей, добавлением в Tools->Database->User Parameters Запись `\?([i|d|s|n|f]|[A|a](\[.+\]|[i|d|s]))`, распространяемую на PHP и SQL.
![image](https://user-images.githubusercontent.com/21163205/77781100-6ae00080-706e-11ea-92d4-756ce1dbb046.png)

Далее, для модифицировал вашу библиотеку,  добавив обработку `?As=0` -- удаление '=0' из запроса (жуткий костыль).
![image](https://user-images.githubusercontent.com/21163205/77781565-39b40000-706f-11ea-98d3-17752bacc6f3.png)


Костылями, предложенным выше, мне удалось минимизировать, как красноту, так и желтизну кода (код ужасен, показывать его не стоит, от него начинает болеть мозг):D
![image](https://user-images.githubusercontent.com/21163205/77781334-d2964b80-706e-11ea-8d26-ec9faed90340.png)
