### ISSUE TITLE
не работает пример с массивами

### ISSUE THREAD

**Issue by geometry88** [Vasiliy-Makogon/Database#6]
```
$user = array('name' => "Д'Артаньян", 'age' => '19', 'adress' => 'замок Кастельмор');
$db->query('INSERT INTO `users` SET ?A["?s", ?i, "?s"]', $user);
```
этот пример не работает, все остальное хорошо работает.
![Безымянный](https://user-images.githubusercontent.com/16748478/119211649-1f7f8180-babc-11eb-9b72-50e3e708192c.png)

**Comment by Vasiliy-Makogon** [comment]
Добрый день, спасибо за обратную связь и прошу прощения, что так поздно.
Действительно, это был баг, вызванный моим скорым исправлением библиотеки под 8 версию.
Поправил.
Фикс лежит в метке v2.0 - https://github.com/Vasiliy-Makogon/Database/tree/V2.0
Для обновления удалите библиотеку через композер и установите заново.
